spring:
  datasource: # mysql配置
    url: jdbc:mysql://127.0.0.1:3306/ts_bdth?useUnicode=true&tinyInt1isBit=false&characterEncoding=utf-8&useSSL=false&serverTimezone =Asia/Shanghai&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
    username: root
    password: 123

  data:
    redis: # redis配置
      database: 0  # Redis数据库索引
      host: 127.0.0.1   # Redis服务器地址
      password: 123
      port: 6379  # Redis服务器连接端口

  cloud: # 注册中心配置
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848



  # 以下为服务器默认配置参数(简单理解为未配置服务器时 使用以下参数)

  # 输出行为
behavior:
  # 作者名称
  author: 时间海
  # Ai自称 建议英文
  botName: bdth
  # 输出语言
  language: 中文
  # 敏感词拦截
  sensitiveWords: CHAT,GPT,OPENAI
  # 敏感词触发时占位符
  sensitiveSymbol: UDP

  # 参数配置
config:
  # 请求地址
  requestUrl: 'https://api.-proxy.com/v1'
  # 低级模型所使用的Key池
  lowLevelKeyList: sk-
  # 高级级模型所使用的Key池
  seniorKeyList: sk-
  # 低级模型列表
  model-list:
    # 模型名称
    - modelName: gpt-3.5-turbo
      # 是否为高级模型
      isSeniorModel: false
      # 调用次数上限 -1无限制
      frequency: 100

    - modelName: gpt-3.5-turbo-16k-0613
      isSeniorModel: false
      frequency: 10
