spring:
  profiles:
    active: @spring.profiles.active@
  application:
    name: chat-server #服务名称

  # mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

  # redis
  data:
    redis:
      timeout: 10s
      lettuce:
        pool:
          max-active: 200  # 连接池最大连接数
          max-wait: -1ms  # 连接池最大阻塞等待时间（使用负值表示没有限制）
          max-idle: 10  # 连接池中的最大空闲连接
          min-idle: 0  # 连接池中的最小空闲连接

#Token配置
sa-token:
  token-prefix: Bearer
  token-name: Authorization

server: #端口号
  port: 9003


mybatis-plus:
  typeAliasesPackage: com.cn.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
    cache-enabled: false
    jdbc-type-for-null: 'null'
