spring:
  data:
    redis: # redis配置
      host: 127.0.0.1   # Redis服务器地址
      port: 6379  # Redis服务器连接端口
      password: 123
  cloud: # 注册中心配置
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    loadbalancer:
      cache:
        enabled: true
        caffeine:
          spec: initialCapacity=500,expireAfterWrite=5s

    gateway: #网关配置
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOriginPatterns:
              - "http://localhost:8080"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
            allowedHeaders:
              - "*"
            allowCredentials: true
            maxAge: 3600
      routes: #配置路由路径
        - id: ts-auth
          uri: lb://auth-server #服务名称
          predicates:
            - Path=/auth-api/**
          filters:
            - StripPrefix=1

        - id: ts-chat
          uri: lb://chat-server #服务名称
          predicates:
            - Path=/chat-api/**
          filters:
            - StripPrefix=1
      discovery:
        locator:
          enabled: true

